version: 0.2

phases:
  install:
    runtime-versions:
    commands:
      - echo Installing Terraform...
      - wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform_1.0.11_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform init

  build:
    commands:
      - echo -- debug --
      - pwd && find . -name "buildspec.yml"
      - echo Validating Terraform configuration...
      - terraform validate
      - echo Planning Terraform changes...
      - terraform plan -out=tfplan
      - echo Applying Terraform changes...
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo Cleaning up Terraform resources...
      - terraform destroy -auto-approve

artifacts:
  files:
    - "**/*"
  discard-paths: yes
